# Site settings
title: The SALA
subtitle: Story
email: youremailaddress@gmail.com
description: SALA Brand Strategy & Positioning and Brand Story
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://verygoodcreative.co" # the base hostname & protocol for your site
author: David Allison Inc
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: Canada
phone: (716) 555-5555

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 7

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
